# Generated by Django 5.1.6 on 2025-02-13 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('rnc', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='company/logos/')),
                ('img_portada', models.ImageField(upload_to='company/portada/')),
                ('email', models.EmailField(max_length=254)),
                ('instagram', models.URLField()),
                ('facebook', models.URLField()),
                ('date', models.DateField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_dynami', models.BooleanField(default=False)),
                ('theme', models.CharField(default='light', max_length=10)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='Company.company')),
            ],
        ),
    ]
