# Generated by Django 5.1.6 on 2025-02-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='interes',
            field=models.IntegerField(default=0),
        ),
    ]
