# Generated by Django 5.1.6 on 2025-02-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_configuration_interes'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='notificaciones',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='porcentaje_mora',
            field=models.IntegerField(default=0),
        ),
    ]
