# Generated by Django 5.1.6 on 2025-02-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_remove_roles_user_roles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('empleado', 'Empleado'), ('contador', 'Contador')], max_length=20),
        ),
    ]
