# Generated by Django 5.1.6 on 2025-02-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0011_alter_more_company_alter_more_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='img_portada',
            field=models.ImageField(blank=True, null=True, upload_to='company/portada/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Nombre de la empresa', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='(000) 000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='rnc',
            field=models.CharField(default='000-0000000-0', max_length=15),
        ),
    ]
