# Generated by Django 5.1.6 on 2025-02-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0012_alter_company_address_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='more',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='more/img/'),
        ),
    ]
