# Generated by Django 5.1.6 on 2025-02-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0014_company_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='interes',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='porcentaje_mora',
        ),
        migrations.AddField(
            model_name='company',
            name='interes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='porcentaje_mora',
            field=models.IntegerField(default=0),
        ),
    ]
