# Generated by Django 5.1.6 on 2025-02-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0016_alter_company_interes_alter_company_porcentaje_mora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='company',
            name='rnc',
            field=models.CharField(default='', max_length=15),
        ),
    ]
