# Generated by Django 5.1.6 on 2025-02-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0017_alter_company_phone_alter_company_rnc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='rnc',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
