# Generated by Django 5.1.6 on 2025-02-28 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0018_alter_company_phone_alter_company_rnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='color_enfasis',
            field=models.CharField(default='#1010101', max_length=15),
        ),
    ]
