# Generated by Django 5.1.6 on 2025-02-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0019_configuration_color_enfasis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='color_enfasis',
            field=models.CharField(default='#101010', max_length=15),
        ),
    ]
