# Generated by Django 5.1.6 on 2025-02-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.AddField(
            model_name='client',
            name='municipios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipios'),
        ),
    ]
