# Generated by Django 5.1.6 on 2025-02-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_remove_client_city_client_municipios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=10, null=True, verbose_name='DNI'),
        ),
    ]
