# Generated by Django 5.1.6 on 2025-02-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_client_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=15, null=True, verbose_name='DNI'),
        ),
    ]
