# Generated by Django 5.1.6 on 2025-02-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_alter_client_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
    ]
