# Generated by Django 5.1.6 on 2025-02-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0006_alter_client_email_alter_client_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True, verbose_name='Sexo'),
        ),
    ]
