# Generated by Django 5.1.6 on 2025-03-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0007_alter_client_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='clients/', verbose_name='Imagen'),
        ),
    ]
