# Generated by Django 5.1.6 on 2025-03-21 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0020_alter_configuration_color_enfasis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Inversion incial', max_length=50, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to='Company.company')),
            ],
        ),
    ]
