# Generated by Django 5.1.6 on 2025-03-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inversion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inversion',
            old_name='amount',
            new_name='mount_inversion',
        ),
        migrations.AddField(
            model_name='inversion',
            name='mount_retorno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
