# Generated by Django 5.1.6 on 2025-03-23 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0020_alter_configuration_color_enfasis'),
        ('Inversion', '0002_rename_amount_inversion_mount_inversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to='Company.company'),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='description',
            field=models.TextField(blank=True, default='Descripcion (opcional)'),
        ),
        migrations.AlterField(
            model_name='inversion',
            name='name',
            field=models.CharField(blank=True, default='Nombra la inversion', max_length=50, null=True),
        ),
    ]
