# Generated by Django 5.1.6 on 2025-03-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inversion', '0004_inversion_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='mount_disponible',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
