# Generated by Django 5.1.6 on 2025-03-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inversion', '0005_inversion_mount_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='mount_prestado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
