# Generated by Django 5.1.6 on 2025-03-27 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Membreship', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plan',
            new_name='Plans',
        ),
    ]
