# Generated by Django 5.1.6 on 2025-03-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membreship', '0002_rename_plan_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='frequency_pay',
            field=models.CharField(choices=[('mes', 'Mensual'), ('trimestral', 'Trimestre'), ('anual', 'Anual')], default='mes', max_length=20),
        ),
    ]
