# Generated by Django 5.1.6 on 2025-03-30 04:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membreship', '0004_alter_carateristica_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_plan', models.CharField(max_length=50)),
                ('price_plan', models.IntegerField(default=0)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('duration_days', models.IntegerField(default=30)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='Membreship.membership')),
            ],
        ),
    ]
