# Generated by Django 5.1.6 on 2025-03-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membreship', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='pending', max_length=10),
        ),
    ]
