# Generated by Django 5.1.6 on 2025-03-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membreship', '0006_payment_invoice_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='id_plan',
            field=models.IntegerField(default=0),
        ),
    ]
