# Generated by Django 5.1.6 on 2025-03-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Membreship', '0007_payment_id_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='id_user',
            field=models.IntegerField(default=0),
        ),
    ]
