# Generated by Django 5.1.6 on 2025-02-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0007_alter_client_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.IntegerField(default=0)),
                ('cuotas', models.IntegerField(default=1)),
                ('intereses', models.IntegerField(default=15)),
                ('frecuecia', models.CharField(choices=[('M', 'Mensuales '), ('S', 'Semanales'), ('Q', 'Quincenales'), ('Tri', 'Trimestrales')], default='M', max_length=50)),
                ('start_date', models.DateField(auto_now=True)),
                ('metodo', models.CharField(choices=[('Frances', 'Aleman'), ('Americano', 'Fijo')], default='Frances', max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cliente', to='Client.client', verbose_name='Credito de un cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(default=0)),
                ('abono', models.IntegerField(default=0)),
                ('mora', models.IntegerField(default=0)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('pagado', models.BooleanField(default=False)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cuotas', to='Credit.credit', verbose_name='Cuotas de un credito')),
            ],
        ),
    ]
