# Generated by Django 5.1.6 on 2025-02-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0002_alter_credit_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='capital',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='credit',
            name='cuotas',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='credit',
            name='metodo',
            field=models.CharField(choices=[('FR', 'Frances'), ('AM', 'Americano'), ('AL', 'Aleman')], max_length=50),
        ),
    ]
