# Generated by Django 5.1.6 on 2025-02-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0003_alter_credit_capital_alter_credit_cuotas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='frecuecia',
            field=models.CharField(choices=[('M', 'Mensuales '), ('S', 'Semanales'), ('Q', 'Quincenales'), ('Tri', 'Trimestrales')], default='FR', max_length=50),
        ),
    ]
