# Generated by Django 5.1.6 on 2025-02-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0004_alter_credit_frecuecia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='frecuecia',
            field=models.CharField(choices=[('M', 'Mensuales '), ('S', 'Semanales'), ('Q', 'Quincenales'), ('Tri', 'Trimestrales')], default='Frances', max_length=50),
        ),
    ]
