# Generated by Django 5.1.6 on 2025-02-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0005_alter_credit_frecuecia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='cuotas',
            field=models.IntegerField(default=0),
        ),
    ]
