# Generated by Django 5.1.6 on 2025-02-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0006_alter_credit_cuotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='cuotas',
            field=models.IntegerField(default=4),
        ),
    ]
