# Generated by Django 5.1.6 on 2025-02-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0007_alter_credit_cuotas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='frecuecia',
            field=models.CharField(choices=[('M', 'Mensuales '), ('S', 'Semanales'), ('Q', 'Quincenales'), ('Tri', 'Trimestrales')], max_length=50),
        ),
    ]
