# Generated by Django 5.1.6 on 2025-02-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0008_alter_credit_frecuecia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credit',
            old_name='frecuecia',
            new_name='frecuencia',
        ),
    ]
