# Generated by Django 5.1.6 on 2025-02-18 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0009_rename_frecuecia_credit_frecuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='frecuencia',
            field=models.CharField(choices=[('mensual', 'Mensuales '), ('semanal', 'Semanales'), ('quincenal', 'Quincenales')], max_length=50),
        ),
        migrations.AlterField(
            model_name='credit',
            name='metodo',
            field=models.CharField(choices=[('frances', 'Frances'), ('americano', 'Americano')], max_length=50),
        ),
    ]
