# Generated by Django 5.1.6 on 2025-02-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0010_alter_credit_frecuencia_alter_credit_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='day_pay',
            field=models.IntegerField(default=30),
        ),
    ]
