# Generated by Django 5.1.6 on 2025-02-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0011_credit_day_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotas',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cuotas',
            name='start_date',
            field=models.DateField(),
        ),
    ]
