# Generated by Django 5.1.6 on 2025-02-21 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0012_alter_cuotas_end_date_alter_cuotas_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='last_pay',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
