# Generated by Django 5.1.6 on 2025-02-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0013_credit_last_pay_credit_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuotas',
            old_name='pagado',
            new_name='payment',
        ),
    ]
