# Generated by Django 5.1.6 on 2025-02-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0014_rename_pagado_cuotas_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotas',
            name='monto_mas_mora',
            field=models.IntegerField(default=0),
        ),
    ]
