# Generated by Django 5.1.6 on 2025-03-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0015_cuotas_monto_mas_mora'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
