# Generated by Django 5.1.6 on 2025-03-31 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0017_credit_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='last_pay',
            field=models.DateField(auto_now_add=True),
        ),
    ]
