# Generated by Django 5.1.6 on 2025-04-02 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Credit', '0018_alter_credit_last_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='last_pay',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
